### ISSUE TITLE
Why put fonts in a separate resource bundle?

### ISSUE THREAD

**Issue by hborders** [CocoaPods-Fonts/OpenSans#4]
https://github.com/CocoaPods-Fonts/OpenSans/blob/master/UIFont%2BOpenSans.m#L19

Why did you put your fonts in a separate resource bundle instead of just leaving them as ordinary resources?

**Comment by kylef** [comment]
@hborders As pre the podspec documentation, resource_bundles is prepared due to name collisions. (This is less relevant now we have frameworks on iOS).

 http://guides.cocoapods.org/syntax/podspec.html#resources

> We strongly recommend library developers to adopt resource bundles as there can be name collisions using the resources attribute. Moreover resources specified with this attribute are copied directly to the client target and therefore they are not optimized by Xcode.

**Comment by hborders** [comment]
That makes sense. So if I'm inside of an iOS framework, I don't really need to worry about these possible collisions anymore I guess.

Thanks!
